name: Full Antora build (based on OSI)
# https://github.com/OpenSimulationInterface/osi-documentation/blob/master/.github/workflows/antora-build.yml
on:
  push:
    branches: [ main ]
# Allow to trigger workflow manually    
  workflow_dispatch:

jobs:
  trigger_antora:
    name: Trigger OpenMATERIAL Antora generator

    runs-on: Ubuntu-latest

    env:
      MUP_KEY: ${{ secrets.ASAM_DISPATCH }}

    steps:
    - name: Trigger Antora generator
      if: ${{ env.MUP_KEY != '' }}
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.ASAM_DISPATCH }} 
        event-type: antora-build-trigger
        repository: nakohdo/openmaterial-antora-generator 
        client-payload: '{"src": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "head_ref": "${{ github.head_ref }}"}'
    
